/* eslint-disable max-len */

const replacers = [
  (source) => source.replaceAll('𝔄', 'A').replaceAll('𝔅', 'B').replaceAll('ℭ', 'C').replaceAll('𝔇', 'D').replaceAll('𝔈', 'E').replaceAll('𝔉', 'F').replaceAll('𝔊', 'G').replaceAll('ℌ', 'H').replaceAll('ℑ', 'I').replaceAll('𝔍', 'J').replaceAll('𝔎', 'K').replaceAll('𝔏', 'L').replaceAll('𝔐', 'M').replaceAll('𝔑', 'N').replaceAll('𝔒', 'O').replaceAll('𝔓', 'P').replaceAll('𝔔', 'Q').replaceAll('ℜ', 'R').replaceAll('𝔖', 'S').replaceAll('𝔗', 'T').replaceAll('𝔘', 'U').replaceAll('𝔙', 'V').replaceAll('𝔚', 'W').replaceAll('𝔛', 'X').replaceAll('𝔜', 'Y').replaceAll('ℨ', 'Z').replaceAll('𝔞', 'a').replaceAll('𝔟', 'b').replaceAll('𝔠', 'c').replaceAll('𝔡', 'd').replaceAll('𝔢', 'e').replaceAll('𝔣', 'f').replaceAll('𝔤', 'g').replaceAll('𝔥', 'h').replaceAll('𝔦', 'i').replaceAll('𝔧', 'j').replaceAll('𝔨', 'k').replaceAll('𝔩', 'l').replaceAll('𝔪', 'm').replaceAll('𝔫', 'n').replaceAll('𝔬', 'o').replaceAll('𝔭', 'p').replaceAll('𝔮', 'q').replaceAll('𝔯', 'r').replaceAll('𝔰', 's').replaceAll('𝔱', 't').replaceAll('𝔲', 'u').replaceAll('𝔳', 'v').replaceAll('𝔴', 'w').replaceAll('𝔵', 'x').replaceAll('𝔶', 'y').replaceAll('𝔷', 'z'),
  (source) => source.replaceAll('𝕬', 'A').replaceAll('𝕭', 'B').replaceAll('𝕮', 'C').replaceAll('𝕯', 'D').replaceAll('𝕰', 'E').replaceAll('𝕱', 'F').replaceAll('𝕲', 'G').replaceAll('𝕳', 'H').replaceAll('𝕴', 'I').replaceAll('𝕵', 'J').replaceAll('𝕶', 'K').replaceAll('𝕷', 'L').replaceAll('𝕸', 'M').replaceAll('𝕹', 'N').replaceAll('𝕺', 'O').replaceAll('𝕻', 'P').replaceAll('𝕼', 'Q').replaceAll('𝕽', 'R').replaceAll('𝕾', 'S').replaceAll('𝕿', 'T').replaceAll('𝖀', 'U').replaceAll('𝖁', 'V').replaceAll('𝖂', 'W').replaceAll('𝖃', 'X').replaceAll('𝖄', 'Y').replaceAll('𝖅', 'Z').replaceAll('𝖆', 'a').replaceAll('𝖇', 'b').replaceAll('𝖈', 'c').replaceAll('𝖉', 'd').replaceAll('𝖊', 'e').replaceAll('𝖋', 'f').replaceAll('𝖌', 'g').replaceAll('𝖍', 'h').replaceAll('𝖎', 'i').replaceAll('𝖏', 'j').replaceAll('𝖐', 'k').replaceAll('𝖑', 'l').replaceAll('𝖒', 'm').replaceAll('𝖓', 'n').replaceAll('𝖔', 'o').replaceAll('𝖕', 'p').replaceAll('𝖖', 'q').replaceAll('𝖗', 'r').replaceAll('𝖘', 's').replaceAll('𝖙', 't').replaceAll('𝖚', 'u').replaceAll('𝖛', 'v').replaceAll('𝖜', 'w').replaceAll('𝖝', 'x').replaceAll('𝖞', 'y').replaceAll('𝖟', 'z'),
  (source) => source.replaceAll('𝓐', 'A').replaceAll('𝓑', 'B').replaceAll('𝓒', 'C').replaceAll('𝓓', 'D').replaceAll('𝓔', 'E').replaceAll('𝓕', 'F').replaceAll('𝓖', 'G').replaceAll('𝓗', 'H').replaceAll('𝓘', 'I').replaceAll('𝓙', 'J').replaceAll('𝓚', 'K').replaceAll('𝓛', 'L').replaceAll('𝓜', 'M').replaceAll('𝓝', 'N').replaceAll('𝓞', 'O').replaceAll('𝓟', 'P').replaceAll('𝓠', 'Q').replaceAll('𝓡', 'R').replaceAll('𝓢', 'S').replaceAll('𝓣', 'T').replaceAll('𝓤', 'U').replaceAll('𝓥', 'V').replaceAll('𝓦', 'W').replaceAll('𝓧', 'X').replaceAll('𝓨', 'Y').replaceAll('𝓩', 'Z').replaceAll('𝓪', 'a').replaceAll('𝓫', 'b').replaceAll('𝓬', 'c').replaceAll('𝓭', 'd').replaceAll('𝓮', 'e').replaceAll('𝓯', 'f').replaceAll('𝓰', 'g').replaceAll('𝓱', 'h').replaceAll('𝓲', 'i').replaceAll('𝓳', 'j').replaceAll('𝓴', 'k').replaceAll('𝓵', 'l').replaceAll('𝓶', 'm').replaceAll('𝓷', 'n').replaceAll('𝓸', 'o').replaceAll('𝓹', 'p').replaceAll('𝓺', 'q').replaceAll('𝓻', 'r').replaceAll('𝓼', 's').replaceAll('𝓽', 't').replaceAll('𝓾', 'u').replaceAll('𝓿', 'v').replaceAll('𝔀', 'w').replaceAll('𝔁', 'x').replaceAll('𝔂', 'y').replaceAll('𝔃', 'z'),
  (source) => source.replaceAll('𝒜', 'A').replaceAll('𝐵', 'B').replaceAll('𝒞', 'C').replaceAll('𝒟', 'D').replaceAll('𝐸', 'E').replaceAll('𝐹', 'F').replaceAll('𝒢', 'G').replaceAll('𝐻', 'H').replaceAll('𝐼', 'I').replaceAll('𝒥', 'J').replaceAll('𝒦', 'K').replaceAll('𝐿', 'L').replaceAll('𝑀', 'M').replaceAll('𝒩', 'N').replaceAll('𝒪', 'O').replaceAll('𝒫', 'P').replaceAll('𝒬', 'Q').replaceAll('𝑅', 'R').replaceAll('𝒮', 'S').replaceAll('𝒯', 'T').replaceAll('𝒰', 'U').replaceAll('𝒱', 'V').replaceAll('𝒲', 'W').replaceAll('𝒳', 'X').replaceAll('𝒴', 'Y').replaceAll('𝒵', 'Z').replaceAll('𝒶', 'a').replaceAll('𝒷', 'b').replaceAll('𝒸', 'c').replaceAll('𝒹', 'd').replaceAll('𝑒', 'e').replaceAll('𝒻', 'f').replaceAll('𝑔', 'g').replaceAll('𝒽', 'h').replaceAll('𝒾', 'i').replaceAll('𝒿', 'j').replaceAll('𝓀', 'k').replaceAll('𝓁', 'l').replaceAll('𝓂', 'm').replaceAll('𝓃', 'n').replaceAll('𝑜', 'o').replaceAll('𝓅', 'p').replaceAll('𝓆', 'q').replaceAll('𝓇', 'r').replaceAll('𝓈', 's').replaceAll('𝓉', 't').replaceAll('𝓊', 'u').replaceAll('𝓋', 'v').replaceAll('𝓌', 'w').replaceAll('𝓍', 'x').replaceAll('𝓎', 'y').replaceAll('𝓏', 'z'),
  (source) => source.replaceAll('𝔸', 'A').replaceAll('𝔹', 'B').replaceAll('ℂ', 'C').replaceAll('𝔻', 'D').replaceAll('𝔼', 'E').replaceAll('𝔽', 'F').replaceAll('𝔾', 'G').replaceAll('ℍ', 'H').replaceAll('𝕀', 'I').replaceAll('𝕁', 'J').replaceAll('𝕂', 'K').replaceAll('𝕃', 'L').replaceAll('𝕄', 'M').replaceAll('ℕ', 'N').replaceAll('𝕆', 'O').replaceAll('ℙ', 'P').replaceAll('ℚ', 'Q').replaceAll('ℝ', 'R').replaceAll('𝕊', 'S').replaceAll('𝕋', 'T').replaceAll('𝕌', 'U').replaceAll('𝕍', 'V').replaceAll('𝕎', 'W').replaceAll('𝕏', 'X').replaceAll('𝕐', 'Y').replaceAll('ℤ', 'Z').replaceAll('𝕒', 'a').replaceAll('𝕓', 'b').replaceAll('𝕔', 'c').replaceAll('𝕕', 'd').replaceAll('𝕖', 'e').replaceAll('𝕗', 'f').replaceAll('𝕘', 'g').replaceAll('𝕙', 'h').replaceAll('𝕚', 'i').replaceAll('𝕛', 'j').replaceAll('𝕜', 'k').replaceAll('𝕝', 'l').replaceAll('𝕞', 'm').replaceAll('𝕟', 'n').replaceAll('𝕠', 'o').replaceAll('𝕡', 'p').replaceAll('𝕢', 'q').replaceAll('𝕣', 'r').replaceAll('𝕤', 's').replaceAll('𝕥', 't').replaceAll('𝕦', 'u').replaceAll('𝕧', 'v').replaceAll('𝕨', 'w').replaceAll('𝕩', 'x').replaceAll('𝕪', 'y').replaceAll('𝕫', 'z'),
  (source) => source.replaceAll('𝘈', 'A').replaceAll('𝘉', 'B').replaceAll('𝘊', 'C').replaceAll('𝘋', 'D').replaceAll('𝘌', 'E').replaceAll('𝘍', 'F').replaceAll('𝘎', 'G').replaceAll('𝘏', 'H').replaceAll('𝘐', 'I').replaceAll('𝘑', 'J').replaceAll('𝘒', 'K').replaceAll('𝘓', 'L').replaceAll('𝘔', 'M').replaceAll('𝘕', 'N').replaceAll('𝘖', 'O').replaceAll('𝘗', 'P').replaceAll('𝘘', 'Q').replaceAll('𝘙', 'R').replaceAll('𝘚', 'S').replaceAll('𝘛', 'T').replaceAll('𝘜', 'U').replaceAll('𝘝', 'V').replaceAll('𝘞', 'W').replaceAll('𝘟', 'X').replaceAll('𝘠', 'Y').replaceAll('𝘡', 'Z').replaceAll('𝘢', 'a').replaceAll('𝘣', 'b').replaceAll('𝘤', 'c').replaceAll('𝘥', 'd').replaceAll('𝘦', 'e').replaceAll('𝘧', 'f').replaceAll('𝘨', 'g').replaceAll('𝘩', 'h').replaceAll('𝘪', 'i').replaceAll('𝘫', 'j').replaceAll('𝘬', 'k').replaceAll('𝘭', 'l').replaceAll('𝘮', 'm').replaceAll('𝘯', 'n').replaceAll('𝘰', 'o').replaceAll('𝘱', 'p').replaceAll('𝘲', 'q').replaceAll('𝘳', 'r').replaceAll('𝘴', 's').replaceAll('𝘵', 't').replaceAll('𝘶', 'u').replaceAll('𝘷', 'v').replaceAll('𝘸', 'w').replaceAll('𝘹', 'x').replaceAll('𝘺', 'y').replaceAll('𝘻', 'z'),
  (source) => source.replaceAll('𝘼', 'A').replaceAll('𝘽', 'B').replaceAll('𝘾', 'C').replaceAll('𝘿', 'D').replaceAll('𝙀', 'E').replaceAll('𝙁', 'F').replaceAll('𝙂', 'G').replaceAll('𝙃', 'H').replaceAll('𝙄', 'I').replaceAll('𝙅', 'J').replaceAll('𝙆', 'K').replaceAll('𝙇', 'L').replaceAll('𝙈', 'M').replaceAll('𝙉', 'N').replaceAll('𝙊', 'O').replaceAll('𝙋', 'P').replaceAll('𝙌', 'Q').replaceAll('𝙍', 'R').replaceAll('𝙎', 'S').replaceAll('𝙏', 'T').replaceAll('𝙐', 'U').replaceAll('𝙑', 'V').replaceAll('𝙒', 'W').replaceAll('𝙓', 'X').replaceAll('𝙔', 'Y').replaceAll('𝙕', 'Z').replaceAll('𝙖', 'a').replaceAll('𝙗', 'b').replaceAll('𝙘', 'c').replaceAll('𝙙', 'd').replaceAll('𝙚', 'e').replaceAll('𝙛', 'f').replaceAll('𝙜', 'g').replaceAll('𝙝', 'h').replaceAll('𝙞', 'i').replaceAll('𝙟', 'j').replaceAll('𝙠', 'k').replaceAll('𝙡', 'l').replaceAll('𝙢', 'm').replaceAll('𝙣', 'n').replaceAll('𝙤', 'o').replaceAll('𝙥', 'p').replaceAll('𝙦', 'q').replaceAll('𝙧', 'r').replaceAll('𝙨', 's').replaceAll('𝙩', 't').replaceAll('𝙪', 'u').replaceAll('𝙫', 'v').replaceAll('𝙬', 'w').replaceAll('𝙭', 'x').replaceAll('𝙮', 'y').replaceAll('𝙯', 'z'),
  (source) => source.replaceAll('𝙰', 'A').replaceAll('𝙱', 'B').replaceAll('𝙲', 'C').replaceAll('𝙳', 'D').replaceAll('𝙴', 'E').replaceAll('𝙵', 'F').replaceAll('𝙶', 'G').replaceAll('𝙷', 'H').replaceAll('𝙸', 'I').replaceAll('𝙹', 'J').replaceAll('𝙺', 'K').replaceAll('𝙻', 'L').replaceAll('𝙼', 'M').replaceAll('𝙽', 'N').replaceAll('𝙾', 'O').replaceAll('𝙿', 'P').replaceAll('𝚀', 'Q').replaceAll('𝚁', 'R').replaceAll('𝚂', 'S').replaceAll('𝚃', 'T').replaceAll('𝚄', 'U').replaceAll('𝚅', 'V').replaceAll('𝚆', 'W').replaceAll('𝚇', 'X').replaceAll('𝚈', 'Y').replaceAll('𝚉', 'Z').replaceAll('𝚊', 'a').replaceAll('𝚋', 'b').replaceAll('𝚌', 'c').replaceAll('𝚍', 'd').replaceAll('𝚎', 'e').replaceAll('𝚏', 'f').replaceAll('𝚐', 'g').replaceAll('𝚑', 'h').replaceAll('𝚒', 'i').replaceAll('𝚓', 'j').replaceAll('𝚔', 'k').replaceAll('𝚕', 'l').replaceAll('𝚖', 'm').replaceAll('𝚗', 'n').replaceAll('𝚘', 'o').replaceAll('𝚙', 'p').replaceAll('𝚚', 'q').replaceAll('𝚛', 'r').replaceAll('𝚜', 's').replaceAll('𝚝', 't').replaceAll('𝚞', 'u').replaceAll('𝚟', 'v').replaceAll('𝚠', 'w').replaceAll('𝚡', 'x').replaceAll('𝚢', 'y').replaceAll('𝚣', 'z'),
  (source) => source.replaceAll('Ⓐ', 'A').replaceAll('Ⓑ', 'B').replaceAll('Ⓒ', 'C').replaceAll('Ⓓ', 'D').replaceAll('Ⓔ', 'E').replaceAll('Ⓕ', 'F').replaceAll('Ⓖ', 'G').replaceAll('Ⓗ', 'H').replaceAll('Ⓘ', 'I').replaceAll('Ⓙ', 'J').replaceAll('Ⓚ', 'K').replaceAll('Ⓛ', 'L').replaceAll('Ⓜ', 'M').replaceAll('Ⓝ', 'N').replaceAll('Ⓞ', 'O').replaceAll('Ⓟ', 'P').replaceAll('Ⓠ', 'Q').replaceAll('Ⓡ', 'R').replaceAll('Ⓢ', 'S').replaceAll('Ⓣ', 'T').replaceAll('Ⓤ', 'U').replaceAll('Ⓥ', 'V').replaceAll('Ⓦ', 'W').replaceAll('Ⓧ', 'X').replaceAll('Ⓨ', 'Y').replaceAll('Ⓩ', 'Z').replaceAll('ⓐ', 'a').replaceAll('ⓑ', 'b').replaceAll('ⓒ', 'c').replaceAll('ⓓ', 'd').replaceAll('ⓔ', 'e').replaceAll('ⓕ', 'f').replaceAll('ⓖ', 'g').replaceAll('ⓗ', 'h').replaceAll('ⓘ', 'i').replaceAll('ⓙ', 'j').replaceAll('ⓚ', 'k').replaceAll('ⓛ', 'l').replaceAll('ⓜ', 'm').replaceAll('ⓝ', 'n').replaceAll('ⓞ', 'o').replaceAll('ⓟ', 'p').replaceAll('ⓠ', 'q').replaceAll('ⓡ', 'r').replaceAll('ⓢ', 's').replaceAll('ⓣ', 't').replaceAll('ⓤ', 'u').replaceAll('ⓥ', 'v').replaceAll('ⓦ', 'w').replaceAll('ⓧ', 'x').replaceAll('ⓨ', 'y').replaceAll('ⓩ', 'z'),
  (source) => source.replaceAll('🅰', 'A').replaceAll('🅱', 'B').replaceAll('🅲', 'C').replaceAll('🅳', 'D').replaceAll('🅴', 'E').replaceAll('🅵', 'F').replaceAll('🅶', 'G').replaceAll('🅷', 'H').replaceAll('🅸', 'I').replaceAll('🅹', 'J').replaceAll('🅺', 'K').replaceAll('🅻', 'L').replaceAll('🅼', 'M').replaceAll('🅽', 'N').replaceAll('🅾', 'O').replaceAll('🅿', 'P').replaceAll('🆀', 'Q').replaceAll('🆁', 'R').replaceAll('🆂', 'S').replaceAll('🆃', 'T').replaceAll('🆄', 'U').replaceAll('🆅', 'V').replaceAll('🆆', 'W').replaceAll('🆇', 'X').replaceAll('🆈', 'Y').replaceAll('🆉', 'Z'),
  (source) => source.replaceAll('ᗩ', 'A').replaceAll('ᗷ', 'B').replaceAll('ᑕ', 'C').replaceAll('ᗪ', 'D').replaceAll('ᗴ', 'E').replaceAll('ᖴ', 'F').replaceAll('Ǥ', 'G').replaceAll('ᕼ', 'H').replaceAll('Ꭵ', 'I').replaceAll('ᒎ', 'J').replaceAll('ᛕ', 'K').replaceAll('ᒪ', 'L').replaceAll('ᗰ', 'M').replaceAll('ᑎ', 'N').replaceAll('ᗝ', 'O').replaceAll('ᑭ', 'P').replaceAll('Ɋ', 'Q').replaceAll('ᖇ', 'R').replaceAll('ᔕ', 'S').replaceAll('丅', 'T').replaceAll('ᑌ', 'U').replaceAll('ᐯ', 'V').replaceAll('ᗯ', 'W').replaceAll('᙭', 'X').replaceAll('Ƴ', 'Y').replaceAll('乙', 'Z'),
  (source) => source.replaceAll('Ａ', 'A').replaceAll('Ｂ', 'B').replaceAll('Ｃ', 'C').replaceAll('Ｄ', 'D').replaceAll('Ｅ', 'E').replaceAll('Ｆ', 'F').replaceAll('Ｇ', 'G').replaceAll('Ｈ', 'H').replaceAll('Ｉ', 'I').replaceAll('Ｊ', 'J').replaceAll('Ｋ', 'K').replaceAll('Ｌ', 'L').replaceAll('Ｍ', 'M').replaceAll('Ｎ', 'N').replaceAll('Ｏ', 'O').replaceAll('Ｐ', 'P').replaceAll('Ｑ', 'Q').replaceAll('Ｒ', 'R').replaceAll('Ｓ', 'S').replaceAll('Ｔ', 'T').replaceAll('Ｕ', 'U').replaceAll('Ｖ', 'V').replaceAll('Ｗ', 'W').replaceAll('Ｘ', 'X').replaceAll('Ｙ', 'Y').replaceAll('Ｚ', 'Z').replaceAll('ａ', 'a').replaceAll('ｂ', 'b').replaceAll('ｃ', 'c').replaceAll('ｄ', 'd').replaceAll('ｅ', 'e').replaceAll('ｆ', 'f').replaceAll('ｇ', 'g').replaceAll('ｈ', 'h').replaceAll('ｉ', 'i').replaceAll('ｊ', 'j').replaceAll('ｋ', 'k').replaceAll('ｌ', 'l').replaceAll('ｍ', 'm').replaceAll('ｎ', 'n').replaceAll('ｏ', 'o').replaceAll('ｐ', 'p').replaceAll('ｑ', 'q').replaceAll('ｒ', 'r').replaceAll('ｓ', 's').replaceAll('ｔ', 't').replaceAll('ｕ', 'u').replaceAll('ｖ', 'v').replaceAll('ｗ', 'w').replaceAll('ｘ', 'x').replaceAll('ｙ', 'y').replaceAll('ｚ', 'z'),
  (source) => source.replaceAll('𝐀', 'A').replaceAll('𝐁', 'B').replaceAll('𝐂', 'C').replaceAll('𝐃', 'D').replaceAll('𝐄', 'E').replaceAll('𝐅', 'F').replaceAll('𝐆', 'G').replaceAll('𝐇', 'H').replaceAll('𝐈', 'I').replaceAll('𝐉', 'J').replaceAll('𝐊', 'K').replaceAll('𝐋', 'L').replaceAll('𝐌', 'M').replaceAll('𝐍', 'N').replaceAll('𝐎', 'O').replaceAll('𝐏', 'P').replaceAll('𝐐', 'Q').replaceAll('𝐑', 'R').replaceAll('𝐒', 'S').replaceAll('𝐓', 'T').replaceAll('𝐔', 'U').replaceAll('𝐕', 'V').replaceAll('𝐖', 'W').replaceAll('𝐗', 'X').replaceAll('𝐘', 'Y').replaceAll('𝐙', 'Z').replaceAll('𝐚', 'a').replaceAll('𝐛', 'b').replaceAll('𝐜', 'c').replaceAll('𝐝', 'd').replaceAll('𝐞', 'e').replaceAll('𝐟', 'f').replaceAll('𝐠', 'g').replaceAll('𝐡', 'h').replaceAll('𝐢', 'i').replaceAll('𝐣', 'j').replaceAll('𝐤', 'k').replaceAll('𝐥', 'l').replaceAll('𝐦', 'm').replaceAll('𝐧', 'n').replaceAll('𝐨', 'o').replaceAll('𝐩', 'p').replaceAll('𝐪', 'q').replaceAll('𝐫', 'r').replaceAll('𝐬', 's').replaceAll('𝐭', 't').replaceAll('𝐮', 'u').replaceAll('𝐯', 'v').replaceAll('𝐰', 'w').replaceAll('𝐱', 'x').replaceAll('𝐲', 'y').replaceAll('𝐳', 'z'),
  (source) => source.replaceAll('ɐ', 'a').replaceAll('ɔ', 'c').replaceAll('ǝ', 'e').replaceAll('ɟ', 'f').replaceAll('ƃ', 'g').replaceAll('ɥ', 'h').replaceAll('ᴉ', 'i').replaceAll('ɾ', 'j').replaceAll('ʞ', 'k').replaceAll('ɯ', 'm').replaceAll('ɹ', 'r').replaceAll('ʇ', 't').replaceAll('ʌ', 'v').replaceAll('ʍ', 'w').replaceAll('ʎ', 'y'),
  (source) => source.replaceAll('🄰', 'A').replaceAll('🄱', 'B').replaceAll('🄲', 'C').replaceAll('🄳', 'D').replaceAll('🄴', 'E').replaceAll('🄵', 'F').replaceAll('🄶', 'G').replaceAll('🄷', 'H').replaceAll('🄸', 'I').replaceAll('🄹', 'J').replaceAll('🄺', 'K').replaceAll('🄻', 'L').replaceAll('🄼', 'M').replaceAll('🄽', 'N').replaceAll('🄾', 'O').replaceAll('🄿', 'P').replaceAll('🅀', 'Q').replaceAll('🅁', 'R').replaceAll('🅂', 'S').replaceAll('🅃', 'T').replaceAll('🅄', 'U').replaceAll('🅅', 'V').replaceAll('🅆', 'W').replaceAll('🅇', 'X').replaceAll('🅈', 'Y').replaceAll('🅉', 'Z'),
];
const testers = [
  /[𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷]/gu,
  /[𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟]/gu,
  /[𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝔀𝔁𝔂𝔃]/gu,
  /[𝒜𝐵𝒞𝒟𝐸𝐹𝒢𝐻𝐼𝒥𝒦𝐿𝑀𝒩𝒪𝒫𝒬𝑅𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹𝑒𝒻𝑔𝒽𝒾𝒿𝓀𝓁𝓂𝓃𝑜𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏]/gu,
  /[𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤ𝕒𝕓𝕔𝕕𝕖𝕗𝕘𝕙𝕚𝕛𝕜𝕝𝕞𝕟𝕠𝕡𝕢𝕣𝕤𝕥𝕦𝕧𝕨𝕩𝕪𝕫]/gu,
  /[𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡𝘢𝘣𝘤𝘥𝘦𝘧𝘨𝘩𝘪𝘫𝘬𝘭𝘮𝘯𝘰𝘱𝘲𝘳𝘴𝘵𝘶𝘷𝘸𝘹𝘺𝘻]/gu,
  /[𝘼𝘽𝘾𝘿𝙀𝙁𝙂𝙃𝙄𝙅𝙆𝙇𝙈𝙉𝙊𝙋𝙌𝙍𝙎𝙏𝙐𝙑𝙒𝙓𝙔𝙕𝙖𝙗𝙘𝙙𝙚𝙛𝙜𝙝𝙞𝙟𝙠𝙡𝙢𝙣𝙤𝙥𝙦𝙧𝙨𝙩𝙪𝙫𝙬𝙭𝙮𝙯]/gu,
  /[𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣]/gu,
  /[ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ]/gu,
  /[🅰🅱🅲🅳🅴🅵🅶🅷🅸🅹🅺🅻🅼🅽🅾🅿🆀🆁🆂🆃🆄🆅🆆🆇🆈🆉]/gu,
  /[ᗩᗷᑕᗪᗴᖴǤᕼᎥᒎᛕᒪᗰᑎᗝᑭɊᖇᔕ丅ᑌᐯᗯ᙭Ƴ乙]/gu,
  /[ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ]/gu,
  /[𝐀𝐁𝐂𝐃𝐄𝐅𝐆𝐇𝐈𝐉𝐊𝐋𝐌𝐍𝐎𝐏𝐐𝐑𝐒𝐓𝐔𝐕𝐖𝐗𝐘𝐙𝐚𝐛𝐜𝐝𝐞𝐟𝐠𝐡𝐢𝐣𝐤𝐥𝐦𝐧𝐨𝐩𝐪𝐫𝐬𝐭𝐮𝐯𝐰𝐱𝐲𝐳]/gu,
  /[ɐɔǝɟƃɥᴉɾʞɯɹʇʌʍʎ]/gu,
  /[🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉]/gu,
];
const normalize = (source) => {
  for (let i=0; i < testers.length; i++) {
    let fancyCount = 0;
    while (testers[i].exec(source)) fancyCount++;
    testers[i].lastIndex = 0;
    if (fancyCount > 3) {
      // console.log('TESTED POSITIVE: ' + i);
      return replacers[i].call(null, source);
    }
  }
  return source;
};

// TEST
// console.log(normalize('Test 𝒜𝐵𝒞𝒟'));

exports.normalize = normalize;
